controllers/EventController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Event;
use app\models\EventSearch;
use app\models\EventPhoto;
use app\models\Polygon;
use app\models\Push;
use app\models\CronPush;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;



/**
 * EventController implements the CRUD actions for Event model.
 */
class EventController extends Controller
{   

    public $layout = '@app/views/layouts/admin';
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
        'access' => [
        'class' => AccessControl::className(),                
        'rules' => [
            [
            'actions' => ['index'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['view'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['create'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['update'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['delete'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['fileupload'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['deleteimage'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['curlpost'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['cronpush'],
            'allow' => true,           
            ],
            
        ],
        ],
        ];
    }


    public function actionCronpush() {
        
        $cronpush = CronPush::find()
            ->all();

        foreach($cronpush as $cron) { 

            echo $cron['id'].'<br>';            
            echo $cron['send'].'<br><br>';            
        }
    }


    public function actionCurlpost() {
        
        //upload file by curl
$url_to_file1 = Yii::$app->basePath . '/web/uploads/w450h4001385925290Cloud.png';
$postFields = array(); 
 
//fileshttp://armageddont/web/apievents
 $postFields['event_photos'] = "@$url_to_file1";
//metaData
$postFields['created_at'] = time();
$postFields['name'] = 'hello_moto';
$postFields['coord_x'] = '55.74';
$postFields['coord_y'] = '37.6';
$postFields['type'] = 1;
$postFields['comment'] = "ilon_mask";
$curl_handle = curl_init();
 
curl_setopt($curl_handle, CURLOPT_URL, 'http://backend.armageddont.kingbird.ru/apievents');
curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl_handle, CURLOPT_POST, true);
curl_setopt($curl_handle, CURLOPT_POSTFIELDS, $postFields);  
//execute the API Call
$server_output = curl_exec($curl_handle);
curl_close ($curl_handle);
if ($server_output == "OK") { echo $server_output; } else { echo $server_output; }

        

      
        /*$alltoken = Push::find()->all();
        foreach($alltoken as $t) { 
            echo $t['device_token'].'<br>';
        }*/




        //test create event   
        /*$json = '[{"photo_name":"foto.png","photo_url":"url"},{"photo_name":"foto.png","photo_url":"url"},{"photo_name":"foto.png","photo_url":"url"},{"photo_name":"foto.png","photo_url":"url"},{"photo_name":"foto.png","photo_url":"url"}]';

        $time = time();
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,"http://armageddont/web/apievents");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,
                    "event_photos=$json&created_at=$time&name=testумуте&type=1&coord_x=55.74&coord_y=37.6&comment=тест_коммент");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $server_output = curl_exec ($ch);
        curl_close ($ch);
        if ($server_output == "OK") { echo $server_output; } else { echo $server_output; }*/


       
        /*$ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,"http://armageddont/web/apipushas");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,
                    "device_token=test&platform=1");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $server_output = curl_exec ($ch);
        curl_close ($ch);
        if ($server_output == "OK") { echo $server_output; } else { echo $server_output; }*/

        //test create event_photos

        /*$time = time();
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,"http://armageddont/web/apitypes");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,
                    "type_name=tessttttypeeeee&type_image=w450h4001385925290Cloud.png&type_image_url=http://s1.iconbird.com/ico/2013/12/505/");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $server_output = curl_exec ($ch);
        curl_close ($ch);
        if ($server_output == "OK") { echo $server_output; } else { echo $server_output; }*/

        //apiphotos
        /*$ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,"http://armageddont/web/apiphotos");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,
                    "event_id=14&photo_name=w450h4001385925290Cloud.png&photo_url=http://s1.iconbird.com/ico/2013/12/505/");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $server_output = curl_exec ($ch);
        curl_close ($ch);
        if ($server_output == "OK") { echo $server_output; } else { echo $server_output; }*/



        /*$ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,"http://backend.armageddont.kingbird.ru/apimessages");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,
                    "event_id=14&created_at=1499167680&user_avatar=https://yt3.ggpht.com/-cMcGrq7WFbM/AAAAAAAAAAI/AAAAAAAAAAA/GbRTISXt768/s100-c-k-no-mo-rj-c0xffffff/photo.jpg&user=Колян&msg=Да....");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $server_output = curl_exec ($ch);
        curl_close ($ch);
        if ($server_output == "OK") { echo $server_output; } else { echo $server_output; }*/

      
    }

    public function beforeAction($action)
    {            
        if ($action->id == 'deleteimage') {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }
   

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EventSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDeleteimage()
    {
        if (Yii::$app->request->isAjax) {
        $data = Yii::$app->request->post();
        $photoId= $data['photoId'];
        $eventId= $data['eventId'];

        $eventPhoto = EventPhoto::findOne($photoId);        
        $eventPhoto->delete(false);
        echo 'good';
        }
    }

    public function actionFileupload()
    {       
       //empty 
    }

    /**
     * Displays a single Event model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

       /* $qwe = 37.62695680957 - rand(1, 3)/1000;        
        echo  $qwe;
        die();*/
        $model = new Event();

        if ( $model->load(Yii::$app->request->post())) {



            $model->created_at = time();

            if ( $model->save() ) { 
                
                //polygon
                $x[1] = $model->coord_x + rand(1, 3)/1000;
                $y[1] = $model->coord_y + rand(1, 3)/1000;

                $x[2] = $model->coord_x - rand(1, 3)/1000;
                $y[2] = $model->coord_y + rand(1, 3)/1000;

                $x[3] = $model->coord_x - rand(1, 3)/1000;
                $y[3] = $model->coord_y - rand(1, 3)/1000;

                $x[4] = $model->coord_x + rand(1, 3)/1000;
                $y[4] = $model->coord_y - rand(1, 3)/1000;                
                
                for ($i = 1; $i <= 4; $i++) {
                    $polygon = new Polygon();
                    $polygon->event_id = $model->id;
                    $polygon->coord_x = $x[$i];
                    $polygon->coord_y = $y[$i];
                    $polygon->save(false);
                }

                $images = UploadedFile::getInstances( $model, 'imageFile');
                
                if(!empty($images)) {
                foreach ($images as $file) {

                    $imageModel = new EventPhoto();
                    $imageModel->photo_name = $file->baseName . '.' . $file->extension;
                    $ext = end((explode(".", $file->baseName . '.' . $file->extension)));
                    $imageModel->photo_name = Yii::$app->security->generateRandomString().".{$ext}";
                    $file->saveAs(Yii::$app->basePath . '/web/uploads/' . $imageModel->photo_name);
                    
                    $imageModel->event_id = $model->id;
                    $imageModel->save();
                    }
                }

                return $this->redirect(['view', 'id' => $model->id]); 
            }
            
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**

controllers/TypeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\EventType;
use app\models\TypeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

/**
 * TypeController implements the CRUD actions for EventType model.
 */
class TypeController extends Controller
{
    public $layout = '@app/views/layouts/admin';
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
        'access' => [
        'class' => AccessControl::className(),                
        'rules' => [
            [
            'actions' => ['index'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['view'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['create'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['update'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['delete'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            
        ],
        ],
        ];
    }

    /**
     * Lists all EventType models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TypeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single EventType model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new EventType model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new EventType();

        if ($model->load(Yii::$app->request->post())) {
            

            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if (!empty($model->imageFile)) {
                $model->upload();
            }            

            if ( $model->save() ) {    
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                'model' => $model,
                ]);
            }

        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }

    }  
        

    /**
     * Updates an existing EventType model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if (!empty($model->imageFile) and $model->imageFile != $model->type_image) {
                $model->upload();
            }

            if ( $model->save() ) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                'model' => $model,
                ]);
            }

        }

        else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing EventType model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the EventType model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return EventType the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = EventType::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/admin.php
<?php

use app\widgets\Alert;
use app\modules\admin\Module;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

/* @var $this \yii\web\View */
/* @var $content string */

/** @var \yii\web\Controller $context */
$context = $this->context;

if (isset($this->params['breadcrumbs'])) {
    $panelBreadcrumbs = [['label' => Module::t('module', 'ADMIN'), 'url' => ['/admin/default/index']]];
    $breadcrumbs = $this->params['breadcrumbs'];
} else {
    $panelBreadcrumbs = [Module::t('module', 'ADMIN')];
    $breadcrumbs = [];
}
?>
<?php $this->beginContent('@app/views/layouts/layout.php'); ?>

<?php
NavBar::begin([
    'brandLabel' => Yii::$app->name,
    'brandUrl' => Yii::$app->homeUrl,
    'options' => [
        'class' => 'navbar-inverse navbar-fixed-top',
    ],
]);
echo Nav::widget([
    'options' => ['class' => 'navbar-nav navbar-right'],
    'activateParents' => true,
    'items' => array_filter([
        ['label' => 'События', 'url' => ['/event/index']],
        ['label' => 'Типы событий', 'url' => ['/type/index']],
        ['label' => 'Сообщения', 'url' => ['/usermessage/index']],

             
        //['label' => Yii::t('app', 'NAV_ADMIN'), 'url' => ['/admin/default/index']],
        ['label' => Yii::t('app', 'NAV_ADMIN_USERS'), 'url' => ['/admin/user/default/index'], 'active' => $context->module->id == 'users'],
        ['label' => Yii::t('app', 'NAV_LOGOUT'), 'url' => ['/user/default/logout'], 'linkOptions' => ['data-method' => 'post']]
    ]),
]);
NavBar::end();
?>

<div class="container">
    <?= Breadcrumbs::widget([
        'links' => ArrayHelper::merge($panelBreadcrumbs, $breadcrumbs),
    ]) ?>
    <?= Alert::widget() ?>
    <?= $content ?>
</div>

<?php $this->endContent(); ?>

views/layouts/layout.php
<?php

use yii\helpers\Html;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">    
    
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>
    <div class="wrap">
        <?= $content ?>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; <?= Yii::$app->name ?></p>
            <p class="pull-right"><?= date('Y') ?></p>
        </div>
    </footer>

<?php $this->endBody() ?>
</body>


</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

use app\widgets\Alert;
use app\modules\admin\rbac\Rbac as AdminRbac;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

/* @var $this \yii\web\View */
/* @var $content string */

?>
<?php $this->beginContent('@app/views/layouts/layout.php'); ?>

<?php
NavBar::begin([
    'brandLabel' => Yii::$app->name,
    'brandUrl' => Yii::$app->homeUrl,
    'options' => [
        'class' => 'navbar-inverse navbar-fixed-top',
    ],
]);
echo Nav::widget([
    'options' => ['class' => 'navbar-nav navbar-right'],
    'activateParents' => true,
    'items' => array_filter([
        ['label' => Yii::t('app', 'NAV_HOME'), 'url' => ['/main/default/index']],
        ['label' => Yii::t('app', 'NAV_CONTACT'), 'url' => ['/main/contact/index']],
        Yii::$app->user->isGuest ?
            ['label' => Yii::t('app', 'NAV_SIGNUP'), 'url' => ['/user/default/signup']] :
            false,
        Yii::$app->user->isGuest ?
            ['label' => Yii::t('app', 'NAV_LOGIN'), 'url' => ['/user/default/login']] :
            false,
        Yii::$app->user->can(AdminRbac::PERMISSION_ADMIN_PANEL) ?
            ['label' => Yii::t('app', 'NAV_ADMIN'), 'url' => ['/admin/default/index']] :
            false,
        !Yii::$app->user->isGuest ?
            ['label' => Yii::t('app', 'NAV_PROFILE'), 'items' => [
                ['label' => Yii::t('app', 'NAV_PROFILE'), 'url' => ['/user/profile/index']],
                ['label' => Yii::t('app', 'NAV_LOGOUT'),
                    'url' => ['/user/default/logout'],
                    'linkOptions' => ['data-method' => 'post']]
            ]] :
            false,
    ]),
]);
NavBar::end();
?>

<div class="container">
    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]) ?>
    <?= Alert::widget() ?>
    <?= $content ?>
</div>

<?php $this->endContent(); ?>