models/Event.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use app\models\EventType;
use app\models\EventPhoto;
use app\models\Polygon;
use app\models\CronPush;
use app\models\Push;


/**
 * This is the model class for table "event".
 *
 * @property integer $id
 * @property integer $created_at
 * @property string $name
 * @property integer $type
 * @property string $coord_x
 * @property string $coord_y
 * @property string $comment
 */
class Event extends \yii\db\ActiveRecord
{   
    public $imageFile;
    public $coordinates;
    public $event_photos;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event';
    }

    public function getEventtype()
    {
        return $this->hasOne(EventType::className(), ['id' => 'type']);

    }

    public function getEventphoto()
    {
        return $this->hasMany(EventPhoto::className(), ['event_id' => 'id']);
    }

    public function getEventpolygon()
    {
        return $this->hasMany(Polygon::className(), ['event_id' => 'id']);
    }
   

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'type', 'coord_x', 'coord_y', 'comment'], 'required'],
            [['danger_level', 'created_at', 'type'], 'integer'],            
            //[['imageFiles'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, gif, jpeg', 'maxFiles' => 10],
            [['imageFile'], 'file', 'skipOnEmpty' => true, 'maxFiles' => 10],
            [['device_token', 'name', 'coord_x', 'coord_y'], 'string', 'max' => 255],
            [['comment', 'coordinates'], 'string', 'max' => 1000],
	    //[['event_photos'], 'file', 'skipOnEmpty' => true],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'created_at' => 'Время создания',
            'imageFile' => 'Добавить картинку',
            'name' => 'Название события',
            'type' => 'Тип события',
            'coord_x' => 'Координата X',
            'coord_y' => 'Координата Y',
            'comment' => 'Комментарий',
            'coordinates' => 'Координаты',
            'danger_level' => 'Уровень опасности',            
            
        ];
    }


    public function fields()
    {
        return [
            
            'id','created_at','name','coord_x','coord_y','comment','danger_level','device_token',
            'event_type_name' => function () {
                if(!empty($this->eventtype->type_name)){ return $this->eventtype->type_name; } else {
                    return '';
                }
                
            },
            /*'event_type_image' => function () {
                return $this->eventtype->type_image;
            },
            'event_type_image_url' => function () {
                return 'http://backend.armageddont.kingbird.ru/uploads/';
            },*/
            'type',           


            'event_photos' => function () {
                return $this->eventphoto;
            },   
            'event_polygons' => function () {
                return $this->eventpolygon;
            },               
        ];
    }


    static function pushas($deviceToken, $message) {
        
        $passphrase = '';
        $pempath = Yii::$app->basePath . '/arm.pem';

        $ctx = stream_context_create();
        stream_context_set_option($ctx, 'ssl', 'local_cert', $pempath);
        //stream_context_set_option($ctx, 'ssl', 'passphrase', $passphrase);

        $fp = stream_socket_client(
          'ssl://gateway.push.apple.com:2195', $err,
          $errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);

        if (!$fp)
          exit("Failed to connect: $err $errstr" . PHP_EOL);
        $body['aps'] = array(
          'alert' => $message,
          'sound' => 'default',
          'link_url' => 'testURL',
          'category' => "NEWS_CATEGORY",
          );
        $payload = json_encode($body);
        $msg = chr(0) . pack('n', 32) . pack('H*', $deviceToken) . pack('n', strlen($payload)) . $payload;
        $result = fwrite($fp, $msg , strlen($msg ));
        fclose($fp);
    }


    static function danger_level($event_id) {
        $danger_level = rand(2, 3);
        \Yii::$app->db->createCommand("UPDATE event SET danger_level=$danger_level WHERE id=:id")
        ->bindValue(':id', $event_id)
        ->execute();
        return $danger_level;
    }

    

 
}

models/EventType.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "event_type".
 *
 * @property integer $id
 * @property integer $event_id
 * @property string $type_name
 * @property string $type_image
 */
class EventType extends \yii\db\ActiveRecord
{

    public $imageFile;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type_name'], 'required'],
            [['imageFile'], 'file', 'skipOnEmpty' => true],
            [['event_id'], 'integer'],
            [['type_name', 'type_image'], 'string', 'max' => 255],
        ];
    }

    

    public function getImage()
    {                     
        return \Yii::$app->request->BaseUrl.'/uploads/'.$this->type_image;          
    }


    public function upload()
    {        
        if ($this->validate()) {

            $this->type_image = $this->imageFile->name;
            $ext = end((explode(".", $this->imageFile->name)));

            $this->type_image = Yii::$app->security->generateRandomString().".{$ext}";
            $path = Yii::$app->basePath . '/web/uploads/' . $this->type_image;
            $this->imageFile->saveAs($path);

            return $this->type_image;
        } else {
            return false;
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'event_id' => 'Event ID',
            'type_name' => 'Имя типа события',
            'type_image' => 'Картинка',
        ];
    }

      public function fields()
    {
        return [
            
            'id','type_name','type_image',
            'type_image_url' => function () {
                return 'http://backend.armageddont.kingbird.ru/uploads/';
            },         
          
        ];
    }
}

controllers/EventController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Event;
use app\models\EventSearch;
use app\models\EventPhoto;
use app\models\Polygon;
use app\models\Push;
use app\models\CronPush;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;



/**
 * EventController implements the CRUD actions for Event model.
 */
class EventController extends Controller
{   

    public $layout = '@app/views/layouts/admin';
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
        'access' => [
        'class' => AccessControl::className(),                
        'rules' => [
            [
            'actions' => ['index'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['view'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['create'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['update'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['delete'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['fileupload'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['deleteimage'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['curlpost'],
            'allow' => true,
            'roles' => ['admin'],
            ],
            [
            'actions' => ['cronpush'],
            'allow' => true,           
            ],
            
        ],
        ],
        ];
    }


    public function actionCronpush() {
        
        $cronpush = CronPush::find()
            ->all();

        foreach($cronpush as $cron) { 

            echo $cron['id'].'<br>';            
            echo $cron['send'].'<br><br>';            
        }
    }


    public function actionCurlpost() {
        
        //upload file by curl
$url_to_file1 = Yii::$app->basePath . '/web/uploads/w450h4001385925290Cloud.png';
$postFields = array(); 
 
//fileshttp://armageddont/web/apievents
 $postFields['event_photos'] = "@$url_to_file1";
//metaData
$postFields['created_at'] = time();
$postFields['name'] = 'hello_moto';
$postFields['coord_x'] = '55.74';
$postFields['coord_y'] = '37.6';
$postFields['type'] = 1;
$postFields['comment'] = "ilon_mask";
$curl_handle = curl_init();
 
curl_setopt($curl_handle, CURLOPT_URL, 'http://backend.armageddont.kingbird.ru/apievents');
curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl_handle, CURLOPT_POST, true);
curl_setopt($curl_handle, CURLOPT_POSTFIELDS, $postFields);  
//execute the API Call
$server_output = curl_exec($curl_handle);
curl_close ($curl_handle);
if ($server_output == "OK") { echo $server_output; } else { echo $server_output; }

        

      
        /*$alltoken = Push::find()->all();
        foreach($alltoken as $t) { 
            echo $t['device_token'].'<br>';
        }*/




        //test create event   
        /*$json = '[{"photo_name":"foto.png","photo_url":"url"},{"photo_name":"foto.png","photo_url":"url"},{"photo_name":"foto.png","photo_url":"url"},{"photo_name":"foto.png","photo_url":"url"},{"photo_name":"foto.png","photo_url":"url"}]';

        $time = time();
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,"http://armageddont/web/apievents");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,
                    "event_photos=$json&created_at=$time&name=testумуте&type=1&coord_x=55.74&coord_y=37.6&comment=тест_коммент");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $server_output = curl_exec ($ch);
        curl_close ($ch);
        if ($server_output == "OK") { echo $server_output; } else { echo $server_output; }*/


       
        /*$ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,"http://armageddont/web/apipushas");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,
                    "device_token=test&platform=1");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $server_output = curl_exec ($ch);
        curl_close ($ch);
        if ($server_output == "OK") { echo $server_output; } else { echo $server_output; }*/

        //test create event_photos

        /*$time = time();
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,"http://armageddont/web/apitypes");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,
                    "type_name=tessttttypeeeee&type_image=w450h4001385925290Cloud.png&type_image_url=http://s1.iconbird.com/ico/2013/12/505/");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $server_output = curl_exec ($ch);
        curl_close ($ch);
        if ($server_output == "OK") { echo $server_output; } else { echo $server_output; }*/

        //apiphotos
        /*$ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,"http://armageddont/web/apiphotos");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,
                    "event_id=14&photo_name=w450h4001385925290Cloud.png&photo_url=http://s1.iconbird.com/ico/2013/12/505/");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $server_output = curl_exec ($ch);
        curl_close ($ch);
        if ($server_output == "OK") { echo $server_output; } else { echo $server_output; }*/



        /*$ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,"http://backend.armageddont.kingbird.ru/apimessages");
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS,
                    "event_id=14&created_at=1499167680&user_avatar=https://yt3.ggpht.com/-cMcGrq7WFbM/AAAAAAAAAAI/AAAAAAAAAAA/GbRTISXt768/s100-c-k-no-mo-rj-c0xffffff/photo.jpg&user=Колян&msg=Да....");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $server_output = curl_exec ($ch);
        curl_close ($ch);
        if ($server_output == "OK") { echo $server_output; } else { echo $server_output; }*/

      
    }

    public function beforeAction($action)
    {            
        if ($action->id == 'deleteimage') {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }
   

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EventSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDeleteimage()
    {
        if (Yii::$app->request->isAjax) {
        $data = Yii::$app->request->post();
        $photoId= $data['photoId'];
        $eventId= $data['eventId'];

        $eventPhoto = EventPhoto::findOne($photoId);        
        $eventPhoto->delete(false);
        echo 'good';
        }
    }

    public function actionFileupload()
    {       
       //empty 
    }

    /**
     * Displays a single Event model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

       /* $qwe = 37.62695680957 - rand(1, 3)/1000;        
        echo  $qwe;
        die();*/
        $model = new Event();

        if ( $model->load(Yii::$app->request->post())) {



            $model->created_at = time();

            if ( $model->save() ) { 
                
                //polygon
                $x[1] = $model->coord_x + rand(1, 3)/1000;
                $y[1] = $model->coord_y + rand(1, 3)/1000;

                $x[2] = $model->coord_x - rand(1, 3)/1000;
                $y[2] = $model->coord_y + rand(1, 3)/1000;

                $x[3] = $model->coord_x - rand(1, 3)/1000;
                $y[3] = $model->coord_y - rand(1, 3)/1000;

                $x[4] = $model->coord_x + rand(1, 3)/1000;
                $y[4] = $model->coord_y - rand(1, 3)/1000;                
                
                for ($i = 1; $i <= 4; $i++) {
                    $polygon = new Polygon();
                    $polygon->event_id = $model->id;
                    $polygon->coord_x = $x[$i];
                    $polygon->coord_y = $y[$i];
                    $polygon->save(false);
                }

                $images = UploadedFile::getInstances( $model, 'imageFile');
                
                if(!empty($images)) {
                foreach ($images as $file) {

                    $imageModel = new EventPhoto();
                    $imageModel->photo_name = $file->baseName . '.' . $file->extension;
                    $ext = end((explode(".", $file->baseName . '.' . $file->extension)));
                    $imageModel->photo_name = Yii::$app->security->generateRandomString().".{$ext}";
                    $file->saveAs(Yii::$app->basePath . '/web/uploads/' . $imageModel->photo_name);
                    
                    $imageModel->event_id = $model->id;
                    $imageModel->save();
                    }
                }

                return $this->redirect(['view', 'id' => $model->id]); 
            }
            
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**

views/event/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\EventType;

use kartik\file\FileInput;
use yii\helpers\Url;
use app\models\EventPhoto;
use yii\bootstrap\Modal;
use app\models\Polygon;

/* @var $this yii\web\View */
/* @var $model app\models\Event */
/* @var $form yii\widgets\ActiveForm */
// AIzaSyDiern53s3oclBm52lQK0F-YWzLWCA_5BU
?>

<div class="event-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>   

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>    

    <?= $form->field($model, 'type')->dropdownList(
    EventType::find()->select(['type_name', 'id'])->indexBy('id')->column(),
    ['prompt'=>'Выберите тип']
    ) ?>

 

    <?php echo $form->field($model, 'danger_level')->dropDownList([
    '1' => 'Cлабый',
    '2' => 'Средний',
    '3'=>'Сильный'
    ]);
    ?>






    <?php

    if(Yii::$app->controller->action->id == 'update') { 
        //перенести поиск в контроллер
        $modelPhoto = EventPhoto::find()       
         ->where(['event_id' => $model->id])
         ->all(); 
        if($modelPhoto) {
        echo '<label class="control-label">Загруженные картинки:</label>';
        echo '<div class="clearfix"></div>';
            foreach($modelPhoto as $photo) {
                echo '   
                <div class="file-preview-frame krajee-default  kv-preview-thumb" id="imageid-'.$photo->id.'" data-fileindex="0" data-template="image"><div class="kv-file-content">
                <img src="/web/uploads/' . $photo->photo_name . '" class="file-preview-image kv-preview-data" title="rss.jpg" alt="rss.jpg" style="width:auto;height:160px;">
                </div><div class="file-thumbnail-footer">
                    <div class="file-footer-caption"></div>
                <div class="file-actions">
                    <div class="file-footer-buttons">
                          <button onclick="DeleteImage('.$photo->id.')" type="button" class="kv-file-zoom btn btn-xs btn-default" title="Удалить"><i class="glyphicon glyphicon-trash"></i></button></div>
                    <div class="clearfix"></div>
                </div>
                </div>
                </div>';
            }
        echo '<div class="clearfix"></div>';
        }
    }  
     
    
    echo $form->field($model, 'imageFile[]')->widget(FileInput::classname(), [
    'options' => ['multiple' => true],
    'pluginOptions' => ['previewFileType' => 'any',
                        'showCaption' => false,
                        'showRemove' => false,
                        'showUpload' => false,]
    ]);
    ?>

    <?php  
    echo $form->field($model, 'coord_x')->textInput(['id'=>'x_coord', 'readonly' => true, 'maxlength' => true,]);
    echo '<button onclick="showmap(); return false;" class="btn btn-info btn-xs">Выбрать координаты</button> ';
    echo $form->field($model, 'coord_y')->textInput(['id'=>'y_coord', 'readonly' => true, 'maxlength' => true,]);
    ?>

    


    <?= $form->field($model, 'comment')->textarea(['rows' => 2, 'cols' => 5]) ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>





 <?php 

     Modal::begin(['id' => 'modal',
        'header' => 'Определение координат метки']);
         echo '<div id="map_canv"></div>';
     Modal::end();
    ?>
   
<?php if(Yii::$app->controller->action->id == 'update') { 
//удалять загруженные ранее фотки можем только в редактировании
  //Все скрипты ниже перенести в registerJS позже
?>

<script>

    function DeleteImage(id) {
        
        $.ajax({
               url: '<?php echo Yii::$app->request->baseUrl. '/event/deleteimage' ?>',
               type: 'post',
               data: {
                         photoId: id, 
                         eventId: <?= $model->id ?>                       
                     },
               success: function (data) {
                  if(data == 'good'){ $('#imageid-' + id).remove(); }
                 
               }
            });
    }
</script>
<?php } ?>

<script>
 function showmap() {
    
    $("#modal").modal("show");
    var $modal = $('#modal'),
    $map = $('#map_canv');
    $modal.on('shown.bs.modal', function () {
      google.maps.event.trigger($map[0], 'resize');        
    });
 }
    
</script>

<script src="https://maps.google.com/maps/api/js?sensor=false&key=AIzaSyDiern53s3oclBm52lQK0F-YWzLWCA_5BU" type="text/javascript"></script>

<style type="text/css" >
      #map_canv {            
            height:500px;
     }
</style>


  <script type="text/javascript">

function initialize() {

            var latlng = new google.maps.LatLng(55.751888, 37.620777);
            var map = new google.maps.Map(document.getElementById('map_canv'), {

            <?php if(Yii::$app->controller->action->id == 'update') { 
                echo 'center: new google.maps.LatLng(' . $model->coord_x . '+ 0.1, ' . $model->coord_y . '- 0.2),';
            } else { ?>
                center: new google.maps.LatLng(55.851888, 37.420777),
            <?php } ?>


                zoom: 11,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });
            var marker = new google.maps.Marker({
            <?php if(Yii::$app->controller->action->id == 'update') { 
                echo 'position: new google.maps.LatLng(' . $model->coord_x . ', ' . $model->coord_y . '),';
            } else { ?>
                position: latlng,
            <?php } ?>
                map: map,
                title: 'Set lat/lon values for this property',
                draggable: true
            });

            google.maps.event.addListener(marker, 'dragend', function (event) {
                document.getElementById("x_coord").value = this.getPosition().lat();
                document.getElementById("y_coord").value = this.getPosition().lng();
                alert('Координаты маркера внесены в форму. Можете закрыть модальное окно.');
            });


   <?php

    if(Yii::$app->controller->action->id == 'update') {            
          
 echo  'var triangleCoords = [';



$polygon = Polygon::find()     
     ->where(['event_id' => $model->id])
     ->all();

foreach($polygon as $val) { echo '{lat: '.$val->coord_x.', lng: '.$val->coord_y.'},';}
?>

    /*{lat: 25.774, lng: -80.190},
    {lat: 18.466, lng: -66.118},
    {lat: 32.321, lng: -64.757},
    {lat: 25.774, lng: -80.190}*/
  ];

  // Construct the polygon.
  var bermudaTriangle = new google.maps.Polygon({
    paths: triangleCoords,
    strokeColor: '#FF0000',
    strokeOpacity: 0.8,
    strokeWeight: 2,
    fillColor: '#FF0000',
    fillOpacity: 0.35
  });
  bermudaTriangle.setMap(map);

<?php 
}
?>
         
}
google.maps.event.addDomListener(window, "load", initialize);







</script>





    

views/event/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EventSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="event-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'type') ?>

    <?= $form->field($model, 'coord_x') ?>

    <?php // echo $form->field($model, 'coord_y') ?>

    <?php // echo $form->field($model, 'comment') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/event/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Event */

$this->title = 'Создание события';
$this->params['breadcrumbs'][] = ['label' => 'События', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/event/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $searchModel app\models\EventSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'События';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-index">

    <h1><?= Html::encode($this->title) ?></h1>
    
    <p>
        <?= Html::a('Создать событие', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',            
            [
                'filter' => false,
                'attribute' => 'created_at',
                'format' => 'datetime',
                'filterOptions' => [
                    'style' => 'max-width: 180px',
                ],
            ],
            'name', 
            'comment',
            [
                'attribute' => 'coord_x',
                'format' => 'html',    
                'filter' => false,
                'header' => 'Координаты',
                'value' => function ($data) {
                    return $data['coord_x'].', <br>'.$data['coord_y'];
                },
            ],
            [
                'filter' => false,
                'attribute' => 'danger_level',               
                'format' => 'html', 
                'value' => function ($data) {
                    if( $data['danger_level'] == 1 ){return 'Слабый';}
                    if( $data['danger_level'] == 2 ){return 'Средний';}
                    if( $data['danger_level'] == 3 ){return 'Сильный';}    
                    
                },
                
            ],
            [
                'attribute' => 'eventtype.type_name',
                'format' => 'html',    
                'value' => function ($data) {
                    return $data['eventtype']['type_name'].' '.Html::img(Yii::getAlias('@web').'/uploads/'. $data['eventtype']['type_image'],
                        ['width' => '20px']);
                },
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/event/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Event */

$this->title = 'Редактирование события: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'События', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редакрирование';
?>
<div class="event-update">

    <h1><?= Html::encode($this->title) ?></h1>

    

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/event/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Event */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'События', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="event-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'created_at',
            'name',
            'type',
            'coord_x',
            'coord_y',
            'comment',
        ],
    ]) ?>

</div>